import os
import nvdlib

from utils.output_print import print_error, print_success, print_progress_bar, print_table, print_info
from utils.file_process import parse_json

# Scan report file generated by whatweb
REPORT_FILENAME=os.path.join("webscan", "scan_report.json")

def discover_cves(params):
    search_params = { "keywordSearch": params }

    # This searches the CVE database for keywords like apache 2.4.4 to find vulnerabilities
    vuln_list = nvdlib.searchCVE(**search_params)
    vuln_count = len(vuln_list)

    if vuln_count > 0:
        # Gets a list of high/critical vulnerabilities
        critical_issues = [
            (cve_data.id, str(cve_data.score[1]), cve_data.score[2], cve_data.url) for cve_data in vuln_list if cve_data.score[2] in ["HIGH", "CRITICAL"]
        ]
        
        # The vulnerabilities are now listed.
        print_error(f"{vuln_count} vulnerability records present", (0, 0))
        if len(critical_issues) > 0:
            print_error(f"{len(critical_issues)} high/critical CVEs found:", (0, 0))
            print_table("",
            [
                { "name": "CVE ID", "style": "info" },
                { "name": "Score", "style": "warning" },
                { "name": "Category", "style": "danger" },
                { "name": "URL", "style": "info" },
            ],
            critical_issues
        )
        else:
            print_success("No high/critical CVEs detected.")
    else:
        # If list is empty, no CVEs are detected.
        print_success("No CVEs detected.")

def loop_through_cves(services):
    for service in services:
        print_info(f"Service found: {service}")
        discover_cves(service)

# This function will read and parse the scan_report.json file
def read_scan_report(filepath):
    # Check if JSON file exists
    if not os.path.exists(filepath):
        print_error("Error: Scan file not found. Try running main.sh and run the scan.")
        return
    try:
        # Pass the scan report and get website details, services and other information
        website_details, services, other_info = parse_json(filepath=filepath)

        # Check if there are any services listed
        if len(services) > 0:
            # Find CVEs associated with the service
            print_progress_bar(loop_through_cves, "[info]Searching for CVEs...", services)
        else:
            print_success("No CVEs detected")
        
        # Print the other information in a table
        print_success(f"More details about {website_details["target"]}:", (0, 0))
        print_table("",
            [
                { "name": "Header info", "style": "info" },
                { "name": "Value", "style": "warning" },
            ],
            [
                (info_key, info_value) for info_key, info_value in other_info.items()
            ]
        )
    except Exception as e:
        # Handle other general errors
        print_error(f"An unexpected error occurred. Check if the website URL is correct.")

read_scan_report(REPORT_FILENAME)