import json
import os
import nvdlib

from utils.output_print import print_error, print_success, print_progress_bar, print_table, print_log

# Scan report file generated by whatweb
REPORT_FILENAME=os.path.join("webscan", "scan_report.json")

def discover_cves(params):
    search_params = { "keywordSearch": params }

    # This searches the CVE database for keywords like apache 2.4.4 to find vulnerabilities
    vuln_list = nvdlib.searchCVE(**search_params)
    vuln_count = len(vuln_list)
    vuln_list[0].url
    if vuln_count > 0:
        # The vulnerabilities are now listed.
        print_error(f"{vuln_count} vulnerability records present, following High/Critical CVEs found:")
        print_table("CVE Vulnerability List",
            [
                { "name": "CVE ID", "style": "info" },
                { "name": "Score", "style": "warning" },
                { "name": "Category", "style": "danger" },
                { "name": "URL", "style": "info" },
            ],
            [
                (cve_data.id, cve_data.score[1], cve_data.score[2], cve_data.url) for cve_data in vuln_list if cve_data.score[2] in ["HIGH", "CRITICAL"]
            ]
        )
    else:
        # If list is empty, no CVEs are detected.
        print_success("No CVEs detected.")

def loop_through_cves(services):
    for service in services:
        print_log(f"Service: {service}")
        discover_cves(service)

# This function will read and parse the information in JSON file
def read_and_parse_json(filepath):
    # Check if JSON file exists
    if not os.path.exists(filepath):
        print_error("Error: Scan file not found. Try running main.sh and run the scan.")
        return
    try:
        with open(filepath, 'r') as file:
            data = json.load(file)
            if isinstance(data, list):
                website_details = data[0]
                services = []
                other_info = {}
                if "plugins" in website_details:
                    plugins_list = website_details["plugins"]
                    for key in plugins_list:
                        if "version" in plugins_list[key]:
                            services.append(key + " " + plugins_list[key]["version"][0])
                        elif "string" in plugins_list[key]:
                            other_info[key] = plugins_list[key]["string"][0]
                
                print_progress_bar(loop_through_cves, "[info]Searching for CVEs...", services)
                print("===========================================================")
                print(f"More details about {website_details["target"]}:")
                for info_key, info_value in other_info.items():
                    print(f"{info_key}: {info_value}")
            # Passing placeholder for now, will make it more dynamic later
            
    except Exception as e:
        # Handle other general errors
        print_error(f"An unexpected error occurred: {e}")

read_and_parse_json(REPORT_FILENAME)