import os
from utils.output_print import print_error, print_console_test, print_info, print_success
from utils.file_process import parse_json
from jinja2 import Environment, FileSystemLoader

# Scan report file generated by whatweb
REPORT_FILENAME=os.path.join("webscan", "scan_report.json")
TEMPLATES_DIR = os.path.join("templates")
OUTPUT_DIR = os.path.join("output")
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "output_html.html")

def is_clickjacking_possible(header_info):
    frame_list = ["SAMEORIGIN", "DENY"]
    if "X-Frame-Options" in header_info or "x-frame-options" in header_info:
        if header_info["X-Frame-Options"] in frame_list or header_info["x-frame-options"] in frame_list:
            return False
        else:
            return True
        
    if "UncommonHeaders" in header_info:
        if "content-security-policy" in header_info["UncommonHeaders"]:
            return False
    
    return True

def clickjacking_test(filepath):
    """
    This function does a clickjacking test on the provided URL

    :param filepath: Path of the file generated by whatweb
    """

    # Check if JSON file exists
    if not os.path.exists(filepath):
        print_error("Error: Scan file not found. Try running main.sh and run the scan.")
        return
    # Pass the scan report and get website details, services and other information
    website_details, _, other_info = parse_json(filepath=filepath)
    print_error("Other info is as follows: ")
    print_console_test(other_info)
    print_info("Checking for clickjacking...")
    clickjacking_support = is_clickjacking_possible(header_info=other_info)
    if clickjacking_support:
        print_success("Clickjacking headers in place.")
    else:
        print_error("No X-Frame-Options or CSP Headers present!")
        data_to_pass = {
            "title": "Jinja Iframe Example",
            # IMPORTANT: The URL must be fully qualified (include http:// or https://)
            "external_url": website_details["target"]
        }

        env = Environment(loader=FileSystemLoader(TEMPLATES_DIR))
        template = env.get_template("clickjacking_template.html")
        rendered_html = template.render(**data_to_pass)
        # 5. Generate the HTML file
        try:
            os.makedirs(OUTPUT_DIR, exist_ok=True)
            with open(OUTPUT_FILE, "w") as f:
                f.write(rendered_html)
            print(f"✅ Successfully generated and saved HTML to {OUTPUT_FILE}")
            print(f"Open '{OUTPUT_FILE}' in your browser to view.")
        except Exception as e:
            print(f"❌ Error writing file: {e}")


clickjacking_test(REPORT_FILENAME)