import os
from utils.output_print import print_error, print_info, print_success
from utils.file_process import parse_json
from flask import Flask, render_template

# Scan report file paths generated by whatweb
REPORT_FILENAME=os.path.join("webscan", "scan_report.json")

# This section sets up a simple Flask server, which would showcase what the website
# looks like without the headers and an example of a website which has clickjacking
# headers set

app = Flask(__name__)

# Route for clickjacking result
@app.route('/')
def home():
    return render_template('clickjacking_template.html', external_url=app.config["WEBSITE_URL"])

# What the result should show
@app.route("/ideal")
def ideal_route():
    return render_template('clickjacking_template.html', external_url="https://www.google.com")

# Setting this will ensure Flask does not show anything in terminal. 
app.logger.disabled = True

def is_clickjacking_possible(header_info):
    frame_list = ["SAMEORIGIN", "DENY"]
    if "X-Frame-Options" in header_info or "x-frame-options" in header_info:
        if header_info["X-Frame-Options"] in frame_list or header_info["x-frame-options"] in frame_list:
            return False
        else:
            return True
    
    if "UncommonHeaders" in header_info:
        if "content-security-policy" in header_info["UncommonHeaders"]:
            return False
    
    return True

def clickjacking_test(filepath):
    """
    This function does a clickjacking test on the provided URL

    :param filepath: Path of the file generated by whatweb
    """

    # Check if JSON file exists
    if not os.path.exists(filepath):
        print_error("Error: Scan file not found. Try running main.sh and run the scan.")
        return
    # Pass the scan report and get website details, services and other information
    website_details, _, other_info = parse_json(filepath=filepath)
    print_info("Checking for clickjacking...")
    clickjacking_support = is_clickjacking_possible(header_info=other_info)
    if not clickjacking_support:
        print_success("Clickjacking headers in place.")
    else:
        print_error("No X-Frame-Options or CSP Headers present! Please wait for the server to start to see the clickjacking page.")

        # This section passes the website URL, so that Flask can run the server and pass
        # this URL in the HTML template.
        app.config["WEBSITE_URL"] = website_details["target"]
        app.run(debug=False)

clickjacking_test(REPORT_FILENAME)