import os
from utils.output_print import print_error, print_console_test
from utils.file_process import parse_json

# Scan report file generated by whatweb
REPORT_FILENAME=os.path.join("webscan", "scan_report.json")

def clickjacking_test(filepath):
    """
    This function does a clickjacking test on the provided URL

    :param filepath: Path of the file generated by whatweb
    """

    # Check if JSON file exists
    if not os.path.exists(filepath):
        print_error("Error: Scan file not found. Try running main.sh and run the scan.")
        return
    # Pass the scan report and get website details, services and other information
    _, _, other_info = parse_json(filepath=filepath)
    print_error("Other info is as follows: ")
    print_console_test(other_info)

clickjacking_test(REPORT_FILENAME)