import json
import os
import nvdlib

# Scan report file generated by whatweb
REPORT_FILENAME="scan_report.json"

def discover_cves(params):
    search_params = { "keywordSearch": params }

    # This searches the CVE database for keywords like apache 2.4.4 to find vulnerabilities
    vuln_list = nvdlib.searchCVE(**search_params)
    vuln_count = len(vuln_list)
    if vuln_count > 0:
        # This filters the list of high or critical vulnerabilities
        critical_list = [
            {"id": cve_data.id, "score": cve_data.score } 
            for cve_data in vuln_list if cve_data.score[2] in ["HIGH", "CRITICAL"]
        ]

        # The vulnerabilities are now listed.
        print(f"\033[91m{vuln_count} vulnerability records present, following High/Critical CVEs found:\033[0m")
        for cve in critical_list:
            print(f"CVE ID: {cve["id"]} | Score: {cve["score"]}")
    else:
        # If list is empty, no CVEs are detected.
        print("No CVEs detected.")

# This function will read and parse the information in JSON file
def read_and_parse_json(filepath):
    # Check if JSON file exists
    if not os.path.exists(filepath):
        print(f"\033[91mError: Scan file not found. Try running main.sh and run the scan.\033[0m")
        return
    try:
        with open(filepath, 'r') as file:
            data = json.load(file)
            if isinstance(data, list):
                website_details = data[0]
                services = []
                other_info = {}
                if "plugins" in website_details:
                    plugins_list = website_details["plugins"]
                    for key in plugins_list:
                        if "version" in plugins_list[key]:
                            services.append(key + " " + plugins_list[key]["version"][0])
                        elif "string" in plugins_list[key]:
                            other_info[key] = plugins_list[key]["string"][0]
                
                print("Checking for CVEs...")
                for service in services:
                    discover_cves(service)
                print("===========================================================")
                print(f"More details about {website_details["target"]}:")
                for info_key, info_value in other_info.items():
                    print(f"{info_key}: {info_value}")
            # Passing placeholder for now, will make it more dynamic later
            
    except Exception as e:
        # Handle other general errors
        print(f"\033[91mAn unexpected error occurred: {e}\033[0m")

read_and_parse_json(REPORT_FILENAME)