import json

def parse_json(json_data_string):
    """
    parse_json takes a JSON string generated by whatweb and then 
    extracts website details, services used and other information

    :param json_data_string: JSON string generated by whatweb
    """
    try:
        data = json.loads(json_data_string)
        if isinstance(data, list):
                website_details = data[0]
                services = []
                other_info = {}
                if "plugins" in website_details:
                    plugins_list = website_details["plugins"]
                    for key in plugins_list:
                        if "version" in plugins_list[key]:
                            services.append(key + " " + plugins_list[key]["version"][0])
                        elif "string" in plugins_list[key]:
                            other_info[key] = plugins_list[key]["string"][0]
                return website_details, services, other_info
    except Exception as e:
        # Handle other general errors
        raise e